.roundbutton{background:url(https://ap1.salesforce.com/resource/1310549700000/ZF_BtnCSS_Img1) no-repeat; font-family:Tahoma, Geneva, sans-serif; font-weight:bold; font-size:12px; border:none; margin-right: 35px; margin-left: 35px; margin-bottom: 35px; margin-top: 15px; cursor:pointer; 
width:158px; height:103px; padding:20px 0px 0px 0px; text-align:center; color:#3f3e3e; text-shadow: 1px 1px 0px #fff; 
background-position:top; white-space: pre-wrap; /* css-3 */ white-space: -moz-pre-wrap; /* Mozilla, since 1999 */white-space: -pre-wrap; /* Opera 4-6 */
white-space: -o-pre-wrap; /* Opera 7 */word-wrap: break-word; /* Internet Explorer 5.5+ */}
.roundbutton:hover{background-position:bottom;}