table.grid {
	border-width: 1px;
	border-spacing: ;
	border-style: outset;
	border-color: gray;
	border-collapse: collapse;
}
table.grid td {
	border-width: 1px;
	border-style: inset;
	border-color: gray;
    border-spacing:;
	padding: 2px;		
}
.currency{border:1px solid #999; width:70px; text-align: right; }
.numeric{border:1px solid #999; width:40px;}
.dropdown{border:1px solid #999; width:150px;}
.lookupField{border:1px solid #999; width:40px;}
.lookupName{border:1px solid #999; width:125px;}
.ref{border:1px solid #999; width:70px;}
.date{border:1px solid #999; width:70px;}
.detailTxtArea{border:1px solid #999; width:175px;}